name: Docker Image CI for MealGenie Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest

      # Save the Docker image to a tar file
    - name: Save Docker image to file
      run: docker save my-image-name:latest -o mealgenie.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v3
      with:
        name: mealgenie-docker-image
        path: mealgenie.tar
